// Generated by gencpp from file vino_pipeline_srv_msgs/PipelineSrvResponse.msg
// DO NOT EDIT!


#ifndef VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINESRVRESPONSE_H
#define VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINESRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vino_pipeline_srv_msgs/Pipelines.h>

namespace vino_pipeline_srv_msgs
{
template <class ContainerAllocator>
struct PipelineSrvResponse_
{
  typedef PipelineSrvResponse_<ContainerAllocator> Type;

  PipelineSrvResponse_()
    : pipelines()  {
    }
  PipelineSrvResponse_(const ContainerAllocator& _alloc)
    : pipelines(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::vino_pipeline_srv_msgs::Pipelines_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vino_pipeline_srv_msgs::Pipelines_<ContainerAllocator> >> _pipelines_type;
  _pipelines_type pipelines;





  typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PipelineSrvResponse_

typedef ::vino_pipeline_srv_msgs::PipelineSrvResponse_<std::allocator<void> > PipelineSrvResponse;

typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineSrvResponse > PipelineSrvResponsePtr;
typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineSrvResponse const> PipelineSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator1> & lhs, const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pipelines == rhs.pipelines;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator1> & lhs, const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vino_pipeline_srv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a26671ca8ad9d84c717232b93bbb1720";
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa26671ca8ad9d84cULL;
  static const uint64_t static_value2 = 0x717232b93bbb1720ULL;
};

template<class ContainerAllocator>
struct DataType< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vino_pipeline_srv_msgs/PipelineSrvResponse";
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pipelines[] pipelines    # return all pipeline status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: vino_pipeline_srv_msgs/Pipelines\n"
"# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"                      \n"
"std_msgs/Header header             # Header\n"
"string name                        # Name of pipeline\n"
"Pipeline[] connections             # connection map of a pipeline\n"
"string running_status              # Pipeline running state\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vino_pipeline_srv_msgs/Pipeline\n"
"# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"                      \n"
"string input                        # From\n"
"string output                       # To\n"
;
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pipelines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PipelineSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vino_pipeline_srv_msgs::PipelineSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "pipelines[]" << std::endl;
    for (size_t i = 0; i < v.pipelines.size(); ++i)
    {
      s << indent << "  pipelines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vino_pipeline_srv_msgs::Pipelines_<ContainerAllocator> >::stream(s, indent + "    ", v.pipelines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINESRVRESPONSE_H
