// Generated by gencpp from file vino_pipeline_srv_msgs/PipelineSrv.msg
// DO NOT EDIT!


#ifndef VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINESRV_H
#define VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINESRV_H

#include <ros/service_traits.h>


#include <vino_pipeline_srv_msgs/PipelineSrvRequest.h>
#include <vino_pipeline_srv_msgs/PipelineSrvResponse.h>


namespace vino_pipeline_srv_msgs
{

struct PipelineSrv
{

typedef PipelineSrvRequest Request;
typedef PipelineSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PipelineSrv
} // namespace vino_pipeline_srv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrv > {
  static const char* value()
  {
    return "cf091771f8906824a3cec7a8b00e6751";
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrv&) { return value(); }
};

template<>
struct DataType< ::vino_pipeline_srv_msgs::PipelineSrv > {
  static const char* value()
  {
    return "vino_pipeline_srv_msgs/PipelineSrv";
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrvRequest> should match
// service_traits::MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrv >
template<>
struct MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrv >::value();
  }
  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_pipeline_srv_msgs::PipelineSrvRequest> should match
// service_traits::DataType< ::vino_pipeline_srv_msgs::PipelineSrv >
template<>
struct DataType< ::vino_pipeline_srv_msgs::PipelineSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vino_pipeline_srv_msgs::PipelineSrv >::value();
  }
  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrvResponse> should match
// service_traits::MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrv >
template<>
struct MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vino_pipeline_srv_msgs::PipelineSrv >::value();
  }
  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_pipeline_srv_msgs::PipelineSrvResponse> should match
// service_traits::DataType< ::vino_pipeline_srv_msgs::PipelineSrv >
template<>
struct DataType< ::vino_pipeline_srv_msgs::PipelineSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vino_pipeline_srv_msgs::PipelineSrv >::value();
  }
  static const char* value(const ::vino_pipeline_srv_msgs::PipelineSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINESRV_H
