// Generated by gencpp from file vino_pipeline_srv_msgs/PipelineRequest.msg
// DO NOT EDIT!


#ifndef VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINEREQUEST_H
#define VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vino_pipeline_srv_msgs
{
template <class ContainerAllocator>
struct PipelineRequest_
{
  typedef PipelineRequest_<ContainerAllocator> Type;

  PipelineRequest_()
    : header()
    , cmd()
    , value()  {
    }
  PipelineRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PipelineRequest_

typedef ::vino_pipeline_srv_msgs::PipelineRequest_<std::allocator<void> > PipelineRequest;

typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineRequest > PipelineRequestPtr;
typedef boost::shared_ptr< ::vino_pipeline_srv_msgs::PipelineRequest const> PipelineRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator1> & lhs, const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cmd == rhs.cmd &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator1> & lhs, const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vino_pipeline_srv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a8ecd5cce85d49ac261250a5fd1af7c";
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a8ecd5cce85d49aULL;
  static const uint64_t static_value2 = 0xc261250a5fd1af7cULL;
};

template<class ContainerAllocator>
struct DataType< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vino_pipeline_srv_msgs/PipelineRequest";
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"                      \n"
"std_msgs/Header header               # Header\n"
"string cmd                           # Name of a request action\n"
"string value                         # value of an action\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PipelineRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vino_pipeline_srv_msgs::PipelineRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VINO_PIPELINE_SRV_MSGS_MESSAGE_PIPELINEREQUEST_H
