// Generated by gencpp from file openface2_ros/Face.msg
// DO NOT EDIT!


#ifndef OPENFACE2_ROS_MESSAGE_FACE_H
#define OPENFACE2_ROS_MESSAGE_FACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace openface2_ros
{
template <class ContainerAllocator>
struct Face_
{
  typedef Face_<ContainerAllocator> Type;

  Face_()
    : header()
    , left_gaze()
    , right_gaze()
    , gaze_angle()
    , head_pos()
    , head_rpy()
    , landmarks_3d()
    , landmarks_2d()  {
    }
  Face_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_gaze(_alloc)
    , right_gaze(_alloc)
    , gaze_angle(_alloc)
    , head_pos(_alloc)
    , head_rpy(_alloc)
    , landmarks_3d(_alloc)
    , landmarks_2d(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _left_gaze_type;
  _left_gaze_type left_gaze;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _right_gaze_type;
  _right_gaze_type right_gaze;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _gaze_angle_type;
  _gaze_angle_type gaze_angle;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _head_pos_type;
  _head_pos_type head_pos;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _head_rpy_type;
  _head_rpy_type head_rpy;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _landmarks_3d_type;
  _landmarks_3d_type landmarks_3d;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _landmarks_2d_type;
  _landmarks_2d_type landmarks_2d;





  typedef boost::shared_ptr< ::openface2_ros::Face_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openface2_ros::Face_<ContainerAllocator> const> ConstPtr;

}; // struct Face_

typedef ::openface2_ros::Face_<std::allocator<void> > Face;

typedef boost::shared_ptr< ::openface2_ros::Face > FacePtr;
typedef boost::shared_ptr< ::openface2_ros::Face const> FaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openface2_ros::Face_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openface2_ros::Face_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openface2_ros::Face_<ContainerAllocator1> & lhs, const ::openface2_ros::Face_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_gaze == rhs.left_gaze &&
    lhs.right_gaze == rhs.right_gaze &&
    lhs.gaze_angle == rhs.gaze_angle &&
    lhs.head_pos == rhs.head_pos &&
    lhs.head_rpy == rhs.head_rpy &&
    lhs.landmarks_3d == rhs.landmarks_3d &&
    lhs.landmarks_2d == rhs.landmarks_2d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openface2_ros::Face_<ContainerAllocator1> & lhs, const ::openface2_ros::Face_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openface2_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::openface2_ros::Face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openface2_ros::Face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openface2_ros::Face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openface2_ros::Face_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openface2_ros::Face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openface2_ros::Face_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openface2_ros::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27d9418620832d6deec93872aa92bbd9";
  }

  static const char* value(const ::openface2_ros::Face_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27d9418620832d6dULL;
  static const uint64_t static_value2 = 0xeec93872aa92bbd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::openface2_ros::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openface2_ros/Face";
  }

  static const char* value(const ::openface2_ros::Face_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openface2_ros::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"geometry_msgs/Pose left_gaze\n"
"geometry_msgs/Pose right_gaze\n"
"\n"
"geometry_msgs/Vector3 gaze_angle\n"
"\n"
"geometry_msgs/Vector3 head_pos\n"
"\n"
"geometry_msgs/Vector3 head_rpy\n"
"\n"
"\n"
"\n"
"geometry_msgs/Point[] landmarks_3d\n"
"geometry_msgs/Point[] landmarks_2d\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::openface2_ros::Face_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openface2_ros::Face_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_gaze);
      stream.next(m.right_gaze);
      stream.next(m.gaze_angle);
      stream.next(m.head_pos);
      stream.next(m.head_rpy);
      stream.next(m.landmarks_3d);
      stream.next(m.landmarks_2d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Face_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openface2_ros::Face_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openface2_ros::Face_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_gaze: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.left_gaze);
    s << indent << "right_gaze: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.right_gaze);
    s << indent << "gaze_angle: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.gaze_angle);
    s << indent << "head_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.head_pos);
    s << indent << "head_rpy: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.head_rpy);
    s << indent << "landmarks_3d[]" << std::endl;
    for (size_t i = 0; i < v.landmarks_3d.size(); ++i)
    {
      s << indent << "  landmarks_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks_3d[i]);
    }
    s << indent << "landmarks_2d[]" << std::endl;
    for (size_t i = 0; i < v.landmarks_2d.size(); ++i)
    {
      s << indent << "  landmarks_2d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks_2d[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENFACE2_ROS_MESSAGE_FACE_H
