# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vino_people_msgs/PeopleSrvRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PeopleSrvRequest(genpy.Message):
  _md5sum = "65568c775bfbc96c6265c3d13d7e1a07"
  _type = "vino_people_msgs/PeopleSrvRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

string image_path       # input: an image
"""
  __slots__ = ['image_path']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       image_path

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PeopleSrvRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.image_path is None:
        self.image_path = ''
    else:
      self.image_path = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.image_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image_path = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.image_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image_path = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vino_people_msgs/PeopleSrvResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import object_msgs.msg
import sensor_msgs.msg
import std_msgs.msg
import vino_people_msgs.msg

class PeopleSrvResponse(genpy.Message):
  _md5sum = "83c4f97addd70470bd4b76248cf735a8"
  _type = "vino_people_msgs/PeopleSrvResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PersonsStamped persons  # output: emotion result



================================================================================
MSG: vino_people_msgs/PersonsStamped
# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

std_msgs/Header header
object_msgs/ObjectInBox[] faces
vino_people_msgs/Emotion[] emotions
vino_people_msgs/AgeGender[] agegenders
vino_people_msgs/HeadPose[] headposes

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: object_msgs/ObjectInBox
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This message can represent a detected object and its region of interest
Object object                     # detected object
sensor_msgs/RegionOfInterest roi  # region of interest

================================================================================
MSG: object_msgs/Object
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This message define the property of detected object
string object_name  # object name
float32 probability # probability of detected object

================================================================================
MSG: sensor_msgs/RegionOfInterest
# This message is used to specify a region of interest within an image.
#
# When used to specify the ROI setting of the camera when the image was
# taken, the height and width fields should either match the height and
# width fields for the associated image; or height = width = 0
# indicates that the full resolution image was captured.

uint32 x_offset  # Leftmost pixel of the ROI
                 # (0 if the ROI includes the left edge of the image)
uint32 y_offset  # Topmost pixel of the ROI
                 # (0 if the ROI includes the top edge of the image)
uint32 height    # Height of ROI
uint32 width     # Width of ROI

# True if a distinct rectified ROI should be calculated from the "raw"
# ROI in this message. Typically this should be False if the full image
# is captured (ROI not used), and True if a subwindow is captured (ROI
# used).
bool do_rectify

================================================================================
MSG: vino_people_msgs/Emotion
# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

string emotion                     # The emotion for the detected face in roi
sensor_msgs/RegionOfInterest roi   # region of interest for a person's face

================================================================================
MSG: vino_people_msgs/AgeGender
# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

float32 age                        # age: 0~100
string gender                      # "Male" or "Female"
float32 gender_confidence          # probability of gender
sensor_msgs/RegionOfInterest roi   # region of interest for a person's face

================================================================================
MSG: vino_people_msgs/HeadPose
# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

float32 yaw							# yaw
float32 pitch						# pitch
float32 roll						# roll
sensor_msgs/RegionOfInterest roi 	# region of interest for a person's face"""
  __slots__ = ['persons']
  _slot_types = ['vino_people_msgs/PersonsStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       persons

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PeopleSrvResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.persons is None:
        self.persons = vino_people_msgs.msg.PersonsStamped()
    else:
      self.persons = vino_people_msgs.msg.PersonsStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.persons.header.seq, _x.persons.header.stamp.secs, _x.persons.header.stamp.nsecs))
      _x = self.persons.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.persons.faces)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.faces:
        _v1 = val1.object
        _x = _v1.object_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v1.probability
        buff.write(_get_struct_f().pack(_x))
        _v2 = val1.roi
        _x = _v2
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
      length = len(self.persons.emotions)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.emotions:
        _x = val1.emotion
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.roi
        _x = _v3
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
      length = len(self.persons.agegenders)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.agegenders:
        _x = val1.age
        buff.write(_get_struct_f().pack(_x))
        _x = val1.gender
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.gender_confidence
        buff.write(_get_struct_f().pack(_x))
        _v4 = val1.roi
        _x = _v4
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
      length = len(self.persons.headposes)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.headposes:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.yaw, _x.pitch, _x.roll))
        _v5 = val1.roi
        _x = _v5
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.persons is None:
        self.persons = vino_people_msgs.msg.PersonsStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.persons.header.seq, _x.persons.header.stamp.secs, _x.persons.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.persons.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.persons.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.faces = []
      for i in range(0, length):
        val1 = object_msgs.msg.ObjectInBox()
        _v6 = val1.object
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v6.object_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v6.object_name = str[start:end]
        start = end
        end += 4
        (_v6.probability,) = _get_struct_f().unpack(str[start:end])
        _v7 = val1.roi
        _x = _v7
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v7.do_rectify = bool(_v7.do_rectify)
        self.persons.faces.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.emotions = []
      for i in range(0, length):
        val1 = vino_people_msgs.msg.Emotion()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.emotion = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.emotion = str[start:end]
        _v8 = val1.roi
        _x = _v8
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v8.do_rectify = bool(_v8.do_rectify)
        self.persons.emotions.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.agegenders = []
      for i in range(0, length):
        val1 = vino_people_msgs.msg.AgeGender()
        start = end
        end += 4
        (val1.age,) = _get_struct_f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.gender = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.gender = str[start:end]
        start = end
        end += 4
        (val1.gender_confidence,) = _get_struct_f().unpack(str[start:end])
        _v9 = val1.roi
        _x = _v9
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v9.do_rectify = bool(_v9.do_rectify)
        self.persons.agegenders.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.headposes = []
      for i in range(0, length):
        val1 = vino_people_msgs.msg.HeadPose()
        _x = val1
        start = end
        end += 12
        (_x.yaw, _x.pitch, _x.roll,) = _get_struct_3f().unpack(str[start:end])
        _v10 = val1.roi
        _x = _v10
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v10.do_rectify = bool(_v10.do_rectify)
        self.persons.headposes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.persons.header.seq, _x.persons.header.stamp.secs, _x.persons.header.stamp.nsecs))
      _x = self.persons.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.persons.faces)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.faces:
        _v11 = val1.object
        _x = _v11.object_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = _v11.probability
        buff.write(_get_struct_f().pack(_x))
        _v12 = val1.roi
        _x = _v12
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
      length = len(self.persons.emotions)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.emotions:
        _x = val1.emotion
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v13 = val1.roi
        _x = _v13
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
      length = len(self.persons.agegenders)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.agegenders:
        _x = val1.age
        buff.write(_get_struct_f().pack(_x))
        _x = val1.gender
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.gender_confidence
        buff.write(_get_struct_f().pack(_x))
        _v14 = val1.roi
        _x = _v14
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
      length = len(self.persons.headposes)
      buff.write(_struct_I.pack(length))
      for val1 in self.persons.headposes:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.yaw, _x.pitch, _x.roll))
        _v15 = val1.roi
        _x = _v15
        buff.write(_get_struct_4IB().pack(_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.persons is None:
        self.persons = vino_people_msgs.msg.PersonsStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.persons.header.seq, _x.persons.header.stamp.secs, _x.persons.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.persons.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.persons.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.faces = []
      for i in range(0, length):
        val1 = object_msgs.msg.ObjectInBox()
        _v16 = val1.object
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v16.object_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v16.object_name = str[start:end]
        start = end
        end += 4
        (_v16.probability,) = _get_struct_f().unpack(str[start:end])
        _v17 = val1.roi
        _x = _v17
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v17.do_rectify = bool(_v17.do_rectify)
        self.persons.faces.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.emotions = []
      for i in range(0, length):
        val1 = vino_people_msgs.msg.Emotion()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.emotion = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.emotion = str[start:end]
        _v18 = val1.roi
        _x = _v18
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v18.do_rectify = bool(_v18.do_rectify)
        self.persons.emotions.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.agegenders = []
      for i in range(0, length):
        val1 = vino_people_msgs.msg.AgeGender()
        start = end
        end += 4
        (val1.age,) = _get_struct_f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.gender = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.gender = str[start:end]
        start = end
        end += 4
        (val1.gender_confidence,) = _get_struct_f().unpack(str[start:end])
        _v19 = val1.roi
        _x = _v19
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v19.do_rectify = bool(_v19.do_rectify)
        self.persons.agegenders.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.persons.headposes = []
      for i in range(0, length):
        val1 = vino_people_msgs.msg.HeadPose()
        _x = val1
        start = end
        end += 12
        (_x.yaw, _x.pitch, _x.roll,) = _get_struct_3f().unpack(str[start:end])
        _v20 = val1.roi
        _x = _v20
        start = end
        end += 17
        (_x.x_offset, _x.y_offset, _x.height, _x.width, _x.do_rectify,) = _get_struct_4IB().unpack(str[start:end])
        _v20.do_rectify = bool(_v20.do_rectify)
        self.persons.headposes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4IB = None
def _get_struct_4IB():
    global _struct_4IB
    if _struct_4IB is None:
        _struct_4IB = struct.Struct("<4IB")
    return _struct_4IB
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
class PeopleSrv(object):
  _type          = 'vino_people_msgs/PeopleSrv'
  _md5sum = '8f01cd199acd34a377ea2e529479a33c'
  _request_class  = PeopleSrvRequest
  _response_class = PeopleSrvResponse
