set(_CATKIN_CURRENT_PACKAGE "vino_param_lib")
set(vino_param_lib_VERSION "0.9.0")
set(vino_param_lib_MAINTAINER "Weizhi Liu <wei.zhi.liu@intel.com>, Chao Li <chao1.li@intel.com>")
set(vino_param_lib_PACKAGE_FORMAT "1")
set(vino_param_lib_BUILD_DEPENDS "yaml-cpp" "roscpp" "roslint")
set(vino_param_lib_BUILD_EXPORT_DEPENDS "yaml-cpp" "roscpp" "roslint")
set(vino_param_lib_BUILDTOOL_DEPENDS "catkin")
set(vino_param_lib_BUILDTOOL_EXPORT_DEPENDS )
set(vino_param_lib_EXEC_DEPENDS "yaml-cpp" "roscpp" "roslint")
set(vino_param_lib_RUN_DEPENDS "yaml-cpp" "roscpp" "roslint")
set(vino_param_lib_TEST_DEPENDS )
set(vino_param_lib_DOC_DEPENDS )
set(vino_param_lib_URL_WEBSITE "")
set(vino_param_lib_URL_BUGTRACKER "")
set(vino_param_lib_URL_REPOSITORY "")
set(vino_param_lib_DEPRECATED "")