# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/AgeGender.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/AgeGenderStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/Emotion.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/EmotionsStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/HeadPose.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/HeadPoseStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/PersonsStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/ObjectInMask.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/ObjectsInMasks.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/Reidentification.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/ReidentificationStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/PersonAttribute.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/PersonAttributeStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/LicensePlate.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/LicensePlateStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/VehicleAttribs.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/VehicleAttribsStamped.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/Landmark.msg;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg/LandmarkStamped.msg"
services_str = "/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/srv/AgeGenderSrv.srv;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/srv/EmotionSrv.srv;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/srv/HeadPoseSrv.srv;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/srv/PeopleSrv.srv;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/srv/ReidentificationSrv.srv;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/srv/ObjectsInMasksSrv.srv"
pkg_name = "vino_people_msgs"
dependencies_str = "std_msgs;sensor_msgs;geometry_msgs;object_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "vino_people_msgs;/home/learnlab/catkin_ws/src/ros_openvino_toolkit/vino_people_msgs/msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;sensor_msgs;/opt/ros/noetic/share/sensor_msgs/cmake/../msg;geometry_msgs;/opt/ros/noetic/share/geometry_msgs/cmake/../msg;object_msgs;/home/learnlab/catkin_ws/src/object_msgs/msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
