set(_CATKIN_CURRENT_PACKAGE "vino_sample")
set(vino_sample_VERSION "0.9.0")
set(vino_sample_MAINTAINER "Weizhi Liu <wei.zhi.liu@intel.com>, Chao Li <chao1.li@intel.com>")
set(vino_sample_PACKAGE_FORMAT "1")
set(vino_sample_BUILD_DEPENDS "roscpp" "roslint" "std_msgs" "vino_core_lib" "vino_param_lib" "cv_bridge" "object_msgs" "openface2_ros" "vino_people_msgs" "vino_pipeline_srv_msgs")
set(vino_sample_BUILD_EXPORT_DEPENDS "roscpp" "roslint" "std_msgs" "sensor_msgs" "cv_bridge" "vino_core_lib" "vino_param_lib" "object_msgs" "openface2_ros" "vino_people_msgs" "vino_pipeline_srv_msgs")
set(vino_sample_BUILDTOOL_DEPENDS "catkin")
set(vino_sample_BUILDTOOL_EXPORT_DEPENDS )
set(vino_sample_EXEC_DEPENDS "roscpp" "roslint" "std_msgs" "sensor_msgs" "cv_bridge" "vino_core_lib" "vino_param_lib" "object_msgs" "openface2_ros" "vino_people_msgs" "vino_pipeline_srv_msgs")
set(vino_sample_RUN_DEPENDS "roscpp" "roslint" "std_msgs" "sensor_msgs" "cv_bridge" "vino_core_lib" "vino_param_lib" "object_msgs" "openface2_ros" "vino_people_msgs" "vino_pipeline_srv_msgs")
set(vino_sample_TEST_DEPENDS )
set(vino_sample_DOC_DEPENDS )
set(vino_sample_URL_WEBSITE "")
set(vino_sample_URL_BUGTRACKER "")
set(vino_sample_URL_REPOSITORY "")
set(vino_sample_DEPRECATED "")