// Generated by gencpp from file vino_people_msgs/AgeGenderSrv.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_AGEGENDERSRV_H
#define VINO_PEOPLE_MSGS_MESSAGE_AGEGENDERSRV_H

#include <ros/service_traits.h>


#include <vino_people_msgs/AgeGenderSrvRequest.h>
#include <vino_people_msgs/AgeGenderSrvResponse.h>


namespace vino_people_msgs
{

struct AgeGenderSrv
{

typedef AgeGenderSrvRequest Request;
typedef AgeGenderSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AgeGenderSrv
} // namespace vino_people_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vino_people_msgs::AgeGenderSrv > {
  static const char* value()
  {
    return "cb3ae0f4f6ae2edd84d46ae3ce84e382";
  }

  static const char* value(const ::vino_people_msgs::AgeGenderSrv&) { return value(); }
};

template<>
struct DataType< ::vino_people_msgs::AgeGenderSrv > {
  static const char* value()
  {
    return "vino_people_msgs/AgeGenderSrv";
  }

  static const char* value(const ::vino_people_msgs::AgeGenderSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vino_people_msgs::AgeGenderSrvRequest> should match
// service_traits::MD5Sum< ::vino_people_msgs::AgeGenderSrv >
template<>
struct MD5Sum< ::vino_people_msgs::AgeGenderSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::AgeGenderSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::AgeGenderSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::AgeGenderSrvRequest> should match
// service_traits::DataType< ::vino_people_msgs::AgeGenderSrv >
template<>
struct DataType< ::vino_people_msgs::AgeGenderSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::AgeGenderSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::AgeGenderSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vino_people_msgs::AgeGenderSrvResponse> should match
// service_traits::MD5Sum< ::vino_people_msgs::AgeGenderSrv >
template<>
struct MD5Sum< ::vino_people_msgs::AgeGenderSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::AgeGenderSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::AgeGenderSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::AgeGenderSrvResponse> should match
// service_traits::DataType< ::vino_people_msgs::AgeGenderSrv >
template<>
struct DataType< ::vino_people_msgs::AgeGenderSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::AgeGenderSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::AgeGenderSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_AGEGENDERSRV_H
