// Generated by gencpp from file vino_people_msgs/EmotionSrv.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_EMOTIONSRV_H
#define VINO_PEOPLE_MSGS_MESSAGE_EMOTIONSRV_H

#include <ros/service_traits.h>


#include <vino_people_msgs/EmotionSrvRequest.h>
#include <vino_people_msgs/EmotionSrvResponse.h>


namespace vino_people_msgs
{

struct EmotionSrv
{

typedef EmotionSrvRequest Request;
typedef EmotionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmotionSrv
} // namespace vino_people_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vino_people_msgs::EmotionSrv > {
  static const char* value()
  {
    return "f96427de68d8e27dc33882099e92670b";
  }

  static const char* value(const ::vino_people_msgs::EmotionSrv&) { return value(); }
};

template<>
struct DataType< ::vino_people_msgs::EmotionSrv > {
  static const char* value()
  {
    return "vino_people_msgs/EmotionSrv";
  }

  static const char* value(const ::vino_people_msgs::EmotionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vino_people_msgs::EmotionSrvRequest> should match
// service_traits::MD5Sum< ::vino_people_msgs::EmotionSrv >
template<>
struct MD5Sum< ::vino_people_msgs::EmotionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::EmotionSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::EmotionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::EmotionSrvRequest> should match
// service_traits::DataType< ::vino_people_msgs::EmotionSrv >
template<>
struct DataType< ::vino_people_msgs::EmotionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::EmotionSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::EmotionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vino_people_msgs::EmotionSrvResponse> should match
// service_traits::MD5Sum< ::vino_people_msgs::EmotionSrv >
template<>
struct MD5Sum< ::vino_people_msgs::EmotionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::EmotionSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::EmotionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::EmotionSrvResponse> should match
// service_traits::DataType< ::vino_people_msgs::EmotionSrv >
template<>
struct DataType< ::vino_people_msgs::EmotionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::EmotionSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::EmotionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_EMOTIONSRV_H
