// Generated by gencpp from file vino_people_msgs/HeadPoseSrv.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_HEADPOSESRV_H
#define VINO_PEOPLE_MSGS_MESSAGE_HEADPOSESRV_H

#include <ros/service_traits.h>


#include <vino_people_msgs/HeadPoseSrvRequest.h>
#include <vino_people_msgs/HeadPoseSrvResponse.h>


namespace vino_people_msgs
{

struct HeadPoseSrv
{

typedef HeadPoseSrvRequest Request;
typedef HeadPoseSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HeadPoseSrv
} // namespace vino_people_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vino_people_msgs::HeadPoseSrv > {
  static const char* value()
  {
    return "00dace25632d42fd75322a75674e8d37";
  }

  static const char* value(const ::vino_people_msgs::HeadPoseSrv&) { return value(); }
};

template<>
struct DataType< ::vino_people_msgs::HeadPoseSrv > {
  static const char* value()
  {
    return "vino_people_msgs/HeadPoseSrv";
  }

  static const char* value(const ::vino_people_msgs::HeadPoseSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vino_people_msgs::HeadPoseSrvRequest> should match
// service_traits::MD5Sum< ::vino_people_msgs::HeadPoseSrv >
template<>
struct MD5Sum< ::vino_people_msgs::HeadPoseSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::HeadPoseSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::HeadPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::HeadPoseSrvRequest> should match
// service_traits::DataType< ::vino_people_msgs::HeadPoseSrv >
template<>
struct DataType< ::vino_people_msgs::HeadPoseSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::HeadPoseSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::HeadPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vino_people_msgs::HeadPoseSrvResponse> should match
// service_traits::MD5Sum< ::vino_people_msgs::HeadPoseSrv >
template<>
struct MD5Sum< ::vino_people_msgs::HeadPoseSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::HeadPoseSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::HeadPoseSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::HeadPoseSrvResponse> should match
// service_traits::DataType< ::vino_people_msgs::HeadPoseSrv >
template<>
struct DataType< ::vino_people_msgs::HeadPoseSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::HeadPoseSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::HeadPoseSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_HEADPOSESRV_H
