// Generated by gencpp from file vino_people_msgs/PeopleSrvResponse.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_PEOPLESRVRESPONSE_H
#define VINO_PEOPLE_MSGS_MESSAGE_PEOPLESRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vino_people_msgs/PersonsStamped.h>

namespace vino_people_msgs
{
template <class ContainerAllocator>
struct PeopleSrvResponse_
{
  typedef PeopleSrvResponse_<ContainerAllocator> Type;

  PeopleSrvResponse_()
    : persons()  {
    }
  PeopleSrvResponse_(const ContainerAllocator& _alloc)
    : persons(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vino_people_msgs::PersonsStamped_<ContainerAllocator>  _persons_type;
  _persons_type persons;





  typedef boost::shared_ptr< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PeopleSrvResponse_

typedef ::vino_people_msgs::PeopleSrvResponse_<std::allocator<void> > PeopleSrvResponse;

typedef boost::shared_ptr< ::vino_people_msgs::PeopleSrvResponse > PeopleSrvResponsePtr;
typedef boost::shared_ptr< ::vino_people_msgs::PeopleSrvResponse const> PeopleSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator1> & lhs, const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.persons == rhs.persons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator1> & lhs, const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vino_people_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83c4f97addd70470bd4b76248cf735a8";
  }

  static const char* value(const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83c4f97addd70470ULL;
  static const uint64_t static_value2 = 0xbd4b76248cf735a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vino_people_msgs/PeopleSrvResponse";
  }

  static const char* value(const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PersonsStamped persons  # output: emotion result\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: vino_people_msgs/PersonsStamped\n"
"# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"std_msgs/Header header\n"
"object_msgs/ObjectInBox[] faces\n"
"vino_people_msgs/Emotion[] emotions\n"
"vino_people_msgs/AgeGender[] agegenders\n"
"vino_people_msgs/HeadPose[] headposes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/ObjectInBox\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent a detected object and its region of interest\n"
"Object object                     # detected object\n"
"sensor_msgs/RegionOfInterest roi  # region of interest\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/Object\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message define the property of detected object\n"
"string object_name  # object name\n"
"float32 probability # probability of detected object\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
"\n"
"================================================================================\n"
"MSG: vino_people_msgs/Emotion\n"
"# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"string emotion                     # The emotion for the detected face in roi\n"
"sensor_msgs/RegionOfInterest roi   # region of interest for a person's face\n"
"\n"
"================================================================================\n"
"MSG: vino_people_msgs/AgeGender\n"
"# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"float32 age                        # age: 0~100\n"
"string gender                      # \"Male\" or \"Female\"\n"
"float32 gender_confidence          # probability of gender\n"
"sensor_msgs/RegionOfInterest roi   # region of interest for a person's face\n"
"\n"
"================================================================================\n"
"MSG: vino_people_msgs/HeadPose\n"
"# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"float32 yaw							# yaw\n"
"float32 pitch						# pitch\n"
"float32 roll						# roll\n"
"sensor_msgs/RegionOfInterest roi 	# region of interest for a person's face\n"
;
  }

  static const char* value(const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.persons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PeopleSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vino_people_msgs::PeopleSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "persons: ";
    s << std::endl;
    Printer< ::vino_people_msgs::PersonsStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.persons);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_PEOPLESRVRESPONSE_H
