// Generated by gencpp from file vino_people_msgs/PeopleSrv.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_PEOPLESRV_H
#define VINO_PEOPLE_MSGS_MESSAGE_PEOPLESRV_H

#include <ros/service_traits.h>


#include <vino_people_msgs/PeopleSrvRequest.h>
#include <vino_people_msgs/PeopleSrvResponse.h>


namespace vino_people_msgs
{

struct PeopleSrv
{

typedef PeopleSrvRequest Request;
typedef PeopleSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PeopleSrv
} // namespace vino_people_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vino_people_msgs::PeopleSrv > {
  static const char* value()
  {
    return "8f01cd199acd34a377ea2e529479a33c";
  }

  static const char* value(const ::vino_people_msgs::PeopleSrv&) { return value(); }
};

template<>
struct DataType< ::vino_people_msgs::PeopleSrv > {
  static const char* value()
  {
    return "vino_people_msgs/PeopleSrv";
  }

  static const char* value(const ::vino_people_msgs::PeopleSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vino_people_msgs::PeopleSrvRequest> should match
// service_traits::MD5Sum< ::vino_people_msgs::PeopleSrv >
template<>
struct MD5Sum< ::vino_people_msgs::PeopleSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::PeopleSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::PeopleSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::PeopleSrvRequest> should match
// service_traits::DataType< ::vino_people_msgs::PeopleSrv >
template<>
struct DataType< ::vino_people_msgs::PeopleSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::PeopleSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::PeopleSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vino_people_msgs::PeopleSrvResponse> should match
// service_traits::MD5Sum< ::vino_people_msgs::PeopleSrv >
template<>
struct MD5Sum< ::vino_people_msgs::PeopleSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::PeopleSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::PeopleSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::PeopleSrvResponse> should match
// service_traits::DataType< ::vino_people_msgs::PeopleSrv >
template<>
struct DataType< ::vino_people_msgs::PeopleSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::PeopleSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::PeopleSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_PEOPLESRV_H
