// Generated by gencpp from file vino_people_msgs/ReidentificationSrvResponse.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_REIDENTIFICATIONSRVRESPONSE_H
#define VINO_PEOPLE_MSGS_MESSAGE_REIDENTIFICATIONSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vino_people_msgs/ReidentificationStamped.h>

namespace vino_people_msgs
{
template <class ContainerAllocator>
struct ReidentificationSrvResponse_
{
  typedef ReidentificationSrvResponse_<ContainerAllocator> Type;

  ReidentificationSrvResponse_()
    : reidentification()  {
    }
  ReidentificationSrvResponse_(const ContainerAllocator& _alloc)
    : reidentification(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vino_people_msgs::ReidentificationStamped_<ContainerAllocator>  _reidentification_type;
  _reidentification_type reidentification;





  typedef boost::shared_ptr< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReidentificationSrvResponse_

typedef ::vino_people_msgs::ReidentificationSrvResponse_<std::allocator<void> > ReidentificationSrvResponse;

typedef boost::shared_ptr< ::vino_people_msgs::ReidentificationSrvResponse > ReidentificationSrvResponsePtr;
typedef boost::shared_ptr< ::vino_people_msgs::ReidentificationSrvResponse const> ReidentificationSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator1> & lhs, const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reidentification == rhs.reidentification;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator1> & lhs, const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vino_people_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "874f6cfd1a618d958c50d9826122260c";
  }

  static const char* value(const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x874f6cfd1a618d95ULL;
  static const uint64_t static_value2 = 0x8c50d9826122260cULL;
};

template<class ContainerAllocator>
struct DataType< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vino_people_msgs/ReidentificationSrvResponse";
  }

  static const char* value(const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ReidentificationStamped reidentification  # ObjectInBox array\n"
"\n"
"\n"
"================================================================================\n"
"MSG: vino_people_msgs/ReidentificationStamped\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent reidentified persons and its IDs\n"
"std_msgs/Header header        			# timestamp in header is the time the sensor captured the raw data\n"
"Reidentification[] reidentified_vector  # ObjectInBox array\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vino_people_msgs/Reidentification\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent a reidentified person and its ID\n"
"string identity  					# person ID\n"
"sensor_msgs/RegionOfInterest roi    # region of interest\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reidentification);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReidentificationSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vino_people_msgs::ReidentificationSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "reidentification: ";
    s << std::endl;
    Printer< ::vino_people_msgs::ReidentificationStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.reidentification);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_REIDENTIFICATIONSRVRESPONSE_H
