// Generated by gencpp from file vino_people_msgs/ReidentificationSrv.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_REIDENTIFICATIONSRV_H
#define VINO_PEOPLE_MSGS_MESSAGE_REIDENTIFICATIONSRV_H

#include <ros/service_traits.h>


#include <vino_people_msgs/ReidentificationSrvRequest.h>
#include <vino_people_msgs/ReidentificationSrvResponse.h>


namespace vino_people_msgs
{

struct ReidentificationSrv
{

typedef ReidentificationSrvRequest Request;
typedef ReidentificationSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReidentificationSrv
} // namespace vino_people_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vino_people_msgs::ReidentificationSrv > {
  static const char* value()
  {
    return "c4b89cb3f0835a54ae60f03c4fb36dc7";
  }

  static const char* value(const ::vino_people_msgs::ReidentificationSrv&) { return value(); }
};

template<>
struct DataType< ::vino_people_msgs::ReidentificationSrv > {
  static const char* value()
  {
    return "vino_people_msgs/ReidentificationSrv";
  }

  static const char* value(const ::vino_people_msgs::ReidentificationSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vino_people_msgs::ReidentificationSrvRequest> should match
// service_traits::MD5Sum< ::vino_people_msgs::ReidentificationSrv >
template<>
struct MD5Sum< ::vino_people_msgs::ReidentificationSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::ReidentificationSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::ReidentificationSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::ReidentificationSrvRequest> should match
// service_traits::DataType< ::vino_people_msgs::ReidentificationSrv >
template<>
struct DataType< ::vino_people_msgs::ReidentificationSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::ReidentificationSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::ReidentificationSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vino_people_msgs::ReidentificationSrvResponse> should match
// service_traits::MD5Sum< ::vino_people_msgs::ReidentificationSrv >
template<>
struct MD5Sum< ::vino_people_msgs::ReidentificationSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vino_people_msgs::ReidentificationSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::ReidentificationSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vino_people_msgs::ReidentificationSrvResponse> should match
// service_traits::DataType< ::vino_people_msgs::ReidentificationSrv >
template<>
struct DataType< ::vino_people_msgs::ReidentificationSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vino_people_msgs::ReidentificationSrv >::value();
  }
  static const char* value(const ::vino_people_msgs::ReidentificationSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_REIDENTIFICATIONSRV_H
