// Generated by gencpp from file vino_people_msgs/VehicleAttribs.msg
// DO NOT EDIT!


#ifndef VINO_PEOPLE_MSGS_MESSAGE_VEHICLEATTRIBS_H
#define VINO_PEOPLE_MSGS_MESSAGE_VEHICLEATTRIBS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/RegionOfInterest.h>

namespace vino_people_msgs
{
template <class ContainerAllocator>
struct VehicleAttribs_
{
  typedef VehicleAttribs_<ContainerAllocator> Type;

  VehicleAttribs_()
    : type()
    , color()
    , roi()  {
    }
  VehicleAttribs_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , color(_alloc)
    , roi(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;

   typedef  ::sensor_msgs::RegionOfInterest_<ContainerAllocator>  _roi_type;
  _roi_type roi;





  typedef boost::shared_ptr< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleAttribs_

typedef ::vino_people_msgs::VehicleAttribs_<std::allocator<void> > VehicleAttribs;

typedef boost::shared_ptr< ::vino_people_msgs::VehicleAttribs > VehicleAttribsPtr;
typedef boost::shared_ptr< ::vino_people_msgs::VehicleAttribs const> VehicleAttribsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator1> & lhs, const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.color == rhs.color &&
    lhs.roi == rhs.roi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator1> & lhs, const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vino_people_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5aaed1102daedd3172759d020a94eaa";
  }

  static const char* value(const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5aaed1102daedd3ULL;
  static const uint64_t static_value2 = 0x172759d020a94eaaULL;
};

template<class ContainerAllocator>
struct DataType< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vino_people_msgs/VehicleAttribs";
  }

  static const char* value(const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2018 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"string type                        # type: car, van, truck, bus\n"
"string color                       # color: blue, gray, yellow, green, black, red, white\n"
"sensor_msgs/RegionOfInterest roi   # region of interest for a vehicle\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.color);
      stream.next(m.roi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleAttribs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vino_people_msgs::VehicleAttribs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vino_people_msgs::VehicleAttribs_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
    s << indent << "roi: ";
    s << std::endl;
    Printer< ::sensor_msgs::RegionOfInterest_<ContainerAllocator> >::stream(s, indent + "  ", v.roi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VINO_PEOPLE_MSGS_MESSAGE_VEHICLEATTRIBS_H
