set(_CATKIN_CURRENT_PACKAGE "openface2_ros")
set(openface2_ros_VERSION "1.0.0")
set(openface2_ros_MAINTAINER "Dito Cahya <dito.cahya@bristol.ac.uk>")
set(openface2_ros_PACKAGE_FORMAT "1")
set(openface2_ros_BUILD_DEPENDS "std_msgs" "geometry_msgs" "sensor_msgs" "message_runtime" "message_generation" "roscpp")
set(openface2_ros_BUILD_EXPORT_DEPENDS "std_msgs" "message_runtime" "roscpp" "sensor_msgs" "geometry_msgs")
set(openface2_ros_BUILDTOOL_DEPENDS "catkin")
set(openface2_ros_BUILDTOOL_EXPORT_DEPENDS )
set(openface2_ros_EXEC_DEPENDS "std_msgs" "message_runtime" "roscpp" "sensor_msgs" "geometry_msgs")
set(openface2_ros_RUN_DEPENDS "std_msgs" "message_runtime" "roscpp" "sensor_msgs" "geometry_msgs")
set(openface2_ros_TEST_DEPENDS )
set(openface2_ros_DOC_DEPENDS )
set(openface2_ros_URL_WEBSITE "")
set(openface2_ros_URL_BUGTRACKER "")
set(openface2_ros_URL_REPOSITORY "")
set(openface2_ros_DEPRECATED "")